name: Tests

jobs:
    tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            -   uses: actions/checkout@v4

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.5'

            -   name: Install root dependencies
                uses: ramsey/composer-install@v3
                with:
                    working-directory: ${{ github.workspace }}

            -   name: Install dependencies
                uses: ramsey/composer-install@v3
                with:
                    working-directory: ux.symfony.com
                    dependency-versions: 'highest'

            -   name: Importmap dependencies
                run: php bin/console importmap:install

            -   name: Build Sass assets
                run: php bin/console sass:build

            -   name: Tests
                run: vendor/bin/phpunit
